services:
  db:
    container_name: eng_postgresql_db
    image: postgres:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
    volumes:
      - eng_postgresql_data:/var/lib/postgresql
    ports:
      - 5433:5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    container_name: eng_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/engapp
      - eng_bundle_data:/usr/local/bundle:cached
      - eng_node_modules:/engapp/node_modules
    environment:
      TZ: Asia/Tokyo
      ENGAPP_DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  eng_bundle_data:
  eng_postgresql_data:
  eng_node_modules: